server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:exams;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=PostgreSQL;
    username: postgres
    password: root
    driverClassName: org.h2.Driver
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true